parameters:
    maesbox_video.provider.video.class: Maesbox\VideoBundle\Provider\VideoProvider

services:
    sonata.media.provider.video:
        class: %maesbox_video.provider.video.class%
        tags:
            - { name: sonata.media.provider }
        arguments:
            - sonata.media.provider.video
            - @sonata.media.filesystem.local
            - @sonata.media.cdn.server
            - @sonata.media.generator.default
            - @sonata.media.thumbnail.format
            - [ flv, mp4, avi, mkv ]
            - [ video/x-flv, video/x-msvideo, video/mp4 ]
            - @sonata.media.resizer.simple
            - @sonata.media.metadata.proxy
        calls:
            - [ setTemplates, [ { helper_thumbnail: MaesboxVideoBundle:Provider:thumbnail.html.twig, helper_view: MaesboxVideoBundle:Provider:video.html.twig } ] ]
        
